# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - winery-mk

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_POSTGRESQL_PASSWORD: ${{ azure-db-env.AZURE_POSTGRESQL_PASSWORD }}
      AZURE_POSTGRESQL_RESOURCE_GROUP: ${{ azure-db-env.AZURE_POSTGRESQL_RESOURCE_GROUP }}
      AZURE_POSTGRESQL_SUBSCRIPTION_ID: ${{ azure-db-env.AZURE_POSTGRESQL_SUBSCRIPTION_ID }}
      AZURE_POSTGRESQL_URL: ${{ azure-db-env.AZURE_POSTGRESQL_URL }}
      AZURE_POSTGRESQL_USERNAME: ${{ azure-db-env.AZURE_POSTGRESQL_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'winery-mk'
          slot-name: 'Production'
          package: '*.war'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F7BB39016250463CA8E8CEFB70759489 }}
